import type { EncounterData } from '../types';

export const encounters: Record<string, EncounterData> = {
  interview_communication: {
    id: 'interview_communication',
    title: 'INTERVIEW ROUND 1',
    enemyName: 'Engagement Manager',
    enemyLevel: 8,
    enemySprite: 'enemy_interview',
    description: 'The engagement manager wants to vet my ability to work with Stakeholders',
    moves: [
      { label: 'Implementation', response: 'Kevin leverages the SDLC Framework for successful implementations' },
      { label: 'Scope Creep', response: 'Kevin avoids scope creep by not comitting to stakeholder asks before working with project leadership' },
      { label: 'Requirements', response: 'Kevin understands busienss personas and tailors communication based on stakeholder' },
      { label: 'Intern Exp', response: 'Kevin has experience floating between plant for operations and back office business units' },
    ],
    victoryText: ['Engagement Manager interview cleared!', 'Strength revealed: BUSINESS COMMUNICATION'],
    setFlag: 'encounter_communication_done',
    processDexEntry: 'business_communication',
    nextEncounterId: 'interview_enterprise',
  },
  interview_enterprise: {
    id: 'interview_enterprise',
    title: 'INTERVIEW ROUND 2',
    enemyName: 'Baker Tilly Partner',
    enemyLevel: 12,
    enemySprite: 'enemy_interview',
    description: 'The partner wants to know Why a career in ERP implementation?',
    moves: [
      { label: 'ERP Architecture', response: 'Kevin shows deep understanding of enterprise systems through coursework!' },
      { label: 'Data Modeling', response: 'Kevin enjoys working with data to understand business processes' },
      { label: 'Cross Functional', response: 'Kevin enjoys working with a wide audience of business partners' },
      { label: 'Pace', response: 'Kevin thrives in fast paced enviornments' },
    ],
    victoryText: ['Kevin earned the respect of consulting leadership!', 'Strength revealed: ENTERPRISE FLUENCY'],
    setFlag: 'encounter_enterprise_done',
    processDexEntry: 'enterprise_fluency',
  },
  bt_edi: {
    id: 'bt_edi',
    title: 'FACTORY CHALLENGE',
    enemyName: 'EDI Chaos',
    enemyLevel: 12,
    enemySprite: 'enemy_bt',
    description: 'EDI transactions are failing across the board!',
    moves: [
      { label: 'Document Mapping', response: 'Kevin configured EDI translation rules — orders flow in cleanly!' },
      { label: 'Trading Partners', response: 'Kevin onboarded every trading partner to standardized EDI!' },
      { label: 'Error Handling', response: 'Kevin built exception handling for malformed documents!' },
      { label: 'AS2 Protocol', response: 'Kevin set up secure AS2 channels for transmission!' },
    ],
    victoryText: ['EDI: standardized!', 'Electronic orders now process automatically.'],
    setFlag: 'enc_bt_edi_done',
    processDexEntry: 'erp_implementation',
  },
  bt_mrp: {
    id: 'bt_mrp',
    title: 'FACTORY CHALLENGE',
    enemyName: 'Material Shortage',
    enemyLevel: 14,
    enemySprite: 'enemy_bt',
    description: 'The production line is starving for parts!',
    moves: [
      { label: 'MRP with BOMs', response: 'Kevin implemented MRP with accurate BOMs and lead times!' },
      { label: 'Safety Stock', response: 'Kevin calculated optimal safety stock levels!' },
      { label: 'Demand Forecast', response: 'Kevin built demand forecasting into the planning cycle!' },
      { label: 'Vendor Scoring', response: 'Kevin ranked suppliers by reliability and lead time!' },
    ],
    victoryText: ['MRP: operational!', 'The right materials arrive at the right time.'],
    setFlag: 'enc_bt_mrp_done',
    processDexEntry: 'erp_implementation',
  },
  bt_cost: {
    id: 'bt_cost',
    title: 'FACTORY CHALLENGE',
    enemyName: 'Cost Black Box',
    enemyLevel: 20,
    description: 'Nobody can trace costs to actual products!',
    moves: [
      { label: 'Activity Costing', response: 'Kevin built a cost model mapping every dollar to its product!' },
      { label: 'Variance Analysis', response: 'Kevin identified cost variances across every work center!' },
      { label: 'Overhead Alloc', response: 'Kevin designed overhead allocation by machine hours!' },
      { label: 'Standard Costing', response: 'Kevin set standard costs and tracked actuals against them!' },
    ],
    victoryText: ['Cost Accounting: transparent!', 'Every dollar is now traceable to a product.'],
    setFlag: 'enc_bt_cost_done',
    processDexEntry: 'erp_implementation',
  },
  dt_manual_audit: {
    id: 'dt_manual_audit',
    title: 'TSA SECURITY CHECK',
    enemyName: 'Manual Audit',
    enemyLevel: 25,
    enemySprite: 'enemy_dt',
    description: 'Wrong answer! TSA is performing a manual audit...',
    moves: [
      { label: 'Compliance', response: 'Kevin demonstrates SOX compliance knowledge!' },
      { label: 'Documentation', response: 'Kevin produces all required documentation!' },
      { label: 'Process Map', response: 'Kevin walks through the process flow!' },
      { label: 'Audit Trail', response: 'Kevin shows a complete audit trail!' },
    ],
    victoryText: ['Audit cleared!', 'But that cost you 30 seconds...'],
  },
  reddit_wild_snoo: {
    id: 'reddit_wild_snoo',
    title: 'WILD ENCOUNTER',
    enemyName: 'Wild Snoo',
    enemyLevel: 40,
    description: 'A wild SNOO appeared in the tall grass!',
    victoryText: ['SNOO joined your team!', 'SNOO will help you navigate Reddit HQ!'],
    setFlag: 'snoo_caught',
    processDexEntry: 'snoo_alien',
    isCatchEncounter: true,
  },

  reddit_work_sox: {
    id: 'reddit_work_sox',
    title: 'WORK ASSIGNMENT',
    enemyName: 'SOX Audit',
    enemyLevel: 35,
    enemySprite: 'enemy_reddit',
    description: 'Quarterly SOX compliance review is due — controls need validation!',
    moves: [
      { label: 'Control Matrix', response: 'Kevin documented all SOX controls in a comprehensive matrix!' },
      { label: 'Access Review', response: 'Kevin completed quarterly access certification — no exceptions!' },
      { label: 'Change Mgmt', response: 'Kevin validated all changes follow the change management process!' },
      { label: 'Audit Trail', response: 'Kevin demonstrated full audit trails for every transaction!' },
    ],
    victoryText: ['SOX audit: passed!', 'Kevin earned $50 for the share price.'],
    moneyReward: 50,
  },

  reddit_work_integration: {
    id: 'reddit_work_integration',
    title: 'WORK ASSIGNMENT',
    enemyName: 'Integration Bug',
    enemyLevel: 38,
    enemySprite: 'enemy_reddit',
    description: 'A critical integration pipeline is broken — data isn\'t flowing!',
    moves: [
      { label: 'API Debug', response: 'Kevin traced the API failure and fixed the authentication token!' },
      { label: 'Data Mapping', response: 'Kevin corrected the field mapping between systems!' },
      { label: 'Error Handling', response: 'Kevin added retry logic and dead letter queues!' },
      { label: 'Monitoring', response: 'Kevin deployed alerting for pipeline health!' },
    ],
    victoryText: ['Integration: restored!', 'Kevin earned $50 for the share price.'],
    moneyReward: 50,
  },

  reddit_work_close: {
    id: 'reddit_work_close',
    title: 'WORK ASSIGNMENT',
    enemyName: 'Month-End Close',
    enemyLevel: 42,
    enemySprite: 'enemy_reddit',
    description: 'Month-end close is in 3 days — subledgers need reconciliation!',
    moves: [
      { label: 'Subledger Rec', response: 'Kevin reconciled all subledger entries against the GL!' },
      { label: 'Accruals', response: 'Kevin automated accrual calculations across all entities!' },
      { label: 'FX Revalue', response: 'Kevin ran foreign currency revaluation for international subs!' },
      { label: 'Close Checklist', response: 'Kevin completed every item on the close checklist — 3 days!' },
    ],
    victoryText: ['Month-end close: done in 3 days!', 'Kevin earned $50 for the share price.'],
    moneyReward: 50,
  },
};
