import type { ProcessDexEntry } from '../types';

export const processDex: Record<string, ProcessDexEntry> = {
  systems_analysis: {
    id: 'systems_analysis',
    title: 'Systems Analysis',
    category: 'Foundation',
    problem: 'Complex operations lack visibility and measurable improvement paths.',
    systems: 'Discrete event simulation, statistical modeling, process mapping',
    result: 'End-to-end system understanding enables targeted optimization.',
    chapter: 'uw_campus',
  },
  business_communication: {
    id: 'business_communication',
    title: 'Business Communication',
    category: 'Foundation',
    problem: 'Sales, Finance, and Engineering speak different languages.',
    systems: 'Process mapping, stakeholder alignment, shared workflow design',
    result: 'Cross-functional teams align on shared processes and data.',
    chapter: 'interview_trail',
  },
  enterprise_fluency: {
    id: 'enterprise_fluency',
    title: 'Enterprise Fluency',
    category: 'Foundation',
    problem: 'Enterprise software is complex and requires deep domain knowledge.',
    systems: 'ERP architecture, MRP logic, enterprise integration patterns',
    result: 'Comfortable navigating and implementing large-scale business systems.',
    chapter: 'interview_trail',
  },
  erp_implementation: {
    id: 'erp_implementation',
    title: 'ERP Implementation',
    category: 'Operations',
    problem: 'Manufacturing operations run on outdated systems and manual processes.',
    systems: 'EDI, MRP, Shop Floor Control, Purchasing, Cost Accounting',
    result: 'End-to-end ERP system reflecting real business requirements.',
    chapter: 'baker_tilly',
  },
  agile_delivery: {
    id: 'agile_delivery',
    title: 'Agile Delivery',
    category: 'Leadership',
    problem: 'Client projects face scope creep and timeline pressure.',
    systems: 'Agile/Scrum, backlog prioritization, sprint planning',
    result: 'Contained scope, on-time delivery, satisfied stakeholders.',
    chapter: 'deloitte_tower',
  },
  integration_platform: {
    id: 'integration_platform',
    title: 'Integration Platform',
    category: 'Architecture',
    problem: 'Legacy workflows rely on manual data transfer between systems.',
    systems: 'Boomi, API integration, middleware, data transformation',
    result: 'Automated data flows replacing manual handoffs.',
    chapter: 'deloitte_tower',
  },
  cost_modeling: {
    id: 'cost_modeling',
    title: 'Cost Modeling',
    category: 'Analytics',
    problem: 'Data center costs are unpredictable and poorly forecasted.',
    systems: 'Financial modeling, forecasting applications, data analysis',
    result: '40% improvement in forecasting accuracy.',
    chapter: 'deloitte_tower',
  },
  pre_ipo_scale: {
    id: 'pre_ipo_scale',
    title: 'Pre-IPO Scale',
    category: 'Architecture',
    problem: 'Order management systems can\'t handle IPO-scale volume.',
    systems: 'Procurement, subscription billing, cash application, Boomi',
    result: 'Scalable order management ready for public company operations.',
    chapter: 'deloitte_tower',
  },
  revenue_recognition: {
    id: 'revenue_recognition',
    title: 'Revenue Recognition',
    category: 'Compliance',
    problem: 'ASC 606 compliance requires complex scenario modeling.',
    systems: 'ASC 606, RPA, revenue automation, audit controls',
    result: 'Automated revenue recognition, audit-ready every quarter.',
    chapter: 'deloitte_tower',
  },
  order_management: {
    id: 'order_management',
    title: 'Order Management',
    category: 'Architecture',
    problem: 'CRM, Ads Platform, and ERP are disconnected.',
    systems: 'CRM integration, order orchestration, quote-to-cash',
    result: 'Unified order management with end-to-end visibility.',
    chapter: 'reddit_hq',
  },
  integration_hub: {
    id: 'integration_hub',
    title: 'Integration Hub',
    category: 'Architecture',
    problem: '20+ finance systems need real-time data exchange.',
    systems: 'Integration management, API orchestration, data validation',
    result: '20+ integrations delivering data where and when needed.',
    chapter: 'reddit_hq',
  },
  subledger_automation: {
    id: 'subledger_automation',
    title: 'Subledger Automation',
    category: 'Automation',
    problem: 'Direct-to-consumer revenue has no automated subledger.',
    systems: 'Subledger design, automated journal entries, reconciliation',
    result: 'Manual entries eliminated. Continuous close capability.',
    chapter: 'reddit_hq',
  },
  data_pipelines: {
    id: 'data_pipelines',
    title: 'Data Pipelines',
    category: 'Analytics',
    problem: 'Finance data is trapped in operational systems.',
    systems: 'NetSuite-to-BigQuery pipelines, real-time analytics',
    result: 'Live financial dashboards powered by automated pipelines.',
    chapter: 'reddit_hq',
  },
  sox_compliance: {
    id: 'sox_compliance',
    title: 'SOX Compliance',
    category: 'Compliance',
    problem: 'System changes lack audit trails and formal controls.',
    systems: 'SOX change control, documentation, approval workflows',
    result: 'Every change is documented, approved, and auditable.',
    chapter: 'reddit_hq',
  },
  close_acceleration: {
    id: 'close_acceleration',
    title: 'Close Acceleration',
    category: 'Impact',
    problem: 'Month-end close takes 12 days of manual work.',
    systems: 'Order management, integrations, subledger, pipelines, SOX controls',
    result: 'Close reduced from 12 days to 3. 75% compression.',
    chapter: 'reddit_hq',
  },
};
